### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by doetlingerlukas** [doetlingerlukas/dotfiles#3]
- [x] Windows Explorer config
- [x] Windows energy profiles
- [x] Customize powershell look
- [x] TeX config
- [x] Steam config

**Comment by doetlingerlukas** [comment]
Done.
